@baseurl=http://localhost:3000

### --- login
POST {{baseurl}}/login
Content-Type: application/json

{
    "email": "fred@mail.io",
    "password": "1234",
    "username": "Fred"
}

### --- Afficher les cartes
GET {{baseurl}}/cards
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYzMjcyNDU2NiwiZXhwIjoxNjMyNzI2MzY2fQ.tdbJC5nh7y8nkWi8N6Zv5nbIjbd5ipBIDZYHkwj7evo

### --- Afficher les favoris par l'id
GET {{baseurl}}/users/5/bookmarks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYzMjY3NDMzNywiZXhwIjoxNjMyNjc2MTM3fQ.OWIzWn5bFNxBpBacsmRLQ_C_UFTfmCiZ9d04yFRWJQQ

### - Ajouter un favori avec l'id de la carte

POST {{baseurl}}/cards/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYzMjY3NDMzNywiZXhwIjoxNjMyNjc2MTM3fQ.OWIzWn5bFNxBpBacsmRLQ_C_UFTfmCiZ9d04yFRWJQQ
